### ISSUE TITLE
Uncaught Error: Call to undefined function Composer\Repository\Pear\simplexml_load_string()

### ISSUE THREAD

**Issue by lrettig** [lrettig/sovereign#3]
Getting this error now on e82c29e49a2fe5a18035f33cc4d01a71b6bb9cda on stretch

```
Cannot create cache directory /var/www/.composer/cache/repo/https---plugins.roundcube.net/, or directory is not writable. Proceeding without cache
Cannot create cache directory /var/www/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /var/www/.composer/cache/files/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Initializing PEAR repository https://pear.php.net
PHP Fatal error:  Uncaught Error: Call to undefined function Composer\Repository\Pear\simplexml_load_string() in /usr/share/php/Composer/Repository/Pear/BaseChannelReader.php:74
Stack trace:
#0 /usr/share/php/Composer/Repository/Pear/ChannelReader.php(53): Composer\Repository\Pear\BaseChannelReader->requestXml('https://pear.ph...', '/channel.xml')
#1 /usr/share/php/Composer/Repository/PearRepository.php(83): Composer\Repository\Pear\ChannelReader->read('https://pear.ph...')
#2 /usr/share/php/Composer/Repository/ArrayRepository.php(185): Composer\Repository\PearRepository->initialize()
#3 /usr/share/php/Composer/DependencyResolver/Pool.php(104): Composer\Repository\ArrayRepository->getPackages()
#4 /usr/share/php/Composer/Installer.php(365): Composer\DependencyResolver\Pool->addRepository(Object(Composer\Repository\PearRepository), Array)
#5 /usr/share/php/Composer/Installer.php(216): Composer\Installer->doInstall(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\Repository\CompositeRepository), Object( in /usr/share/php/Composer/Repository/Pear/BaseChannelReader.php on line 74
```

**Comment by lrettig** [comment]
Looks like a missing PHP package... https://stackoverflow.com/questions/31206186/call-to-undefined-function-simplexml-load-string

**Comment by lrettig** [comment]
Worked around this for now by disabling `webmail` in `site.yml`
